version: '3.9'
services:
  app:
    image: phathdt379/go-hello:v1
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api_json_errors.conf:/etc/nginx/api_json_errors.conf
    depends_on:
      - app
    ports:
      - '80:80'
